### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by princekumarg**

### CODE REVIEW

**Comment by princekumarg** [comment]
@thelegendavanish can you make the merge the PR.

**Comment by princekumarg** [comment]
i want Q)CSS Transform Skew answer.

**Comment by princekumarg** [comment]
@thelegendavanish i had made Some Change in your repository please see this and merged that issue.

**Comment by thelegendavanish** [comment]
> i want Q)CSS Transform Skew answer.

#box {
    /* Use Transform Skew in here to match box exact to the skeleton */
     transform: skew(5deg,50deg);
    /* --- */

    position: absolute;
    z-index: 2;
    height: 100px;
    width: 100px;
    background-color: palevioletred;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    margin: auto;
}

**Comment by thelegendavanish** [comment]
> i want Q)CSS Transform Skew answer.

#box {
    /* Use Transform Skew in here to match box exact to the skeleton */
     transform: skew(5deg,50deg);
    /* --- */
    position: absolute;
    z-index: 2;
    height: 100px;
    width: 100px;
    background-color: palevioletred;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    margin: auto;
}

**Comment by princekumarg** [comment]
thk bro

**Pull request merged**
